export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'

export const ADD_ITEM_PLACEHOLDER = 'ADD_ITEM_PLACEHOLDER'
export const REMOVE_ITEM_PLACEHOLDER = 'REMOVE_ITEM_PLACEHOLDER'

export const CLEAR_DARUMA = 'CLEAR_DARUMA'
